### ISSUE TITLE
There is a lag problem

### ISSUE THREAD

**Issue by CatzTimes** [ShimmyMySherbet/UnturnedConsoleMetrics#1]
I have been using this plug-in for a while, and I found that this plug-in has a probability of causing the background log to be stuck
And it has a certain effect on the server, can you consider optimizing it?

**Comment by ShimmyMySherbet** [comment]
>  background log to be stuck

> a certain effect on the server

Could you please elaborate on these issues your experiencing?

**Comment by CatzTimes** [comment]
It is sometimes found that the background log shows that it was stuck at a previous time。
When I press enter it will resume

**Comment by ShimmyMySherbet** [comment]
It sounds like you are selecting text in the command window.
Doing this prevents anything from being written to the command window, suspending the game.

If this is the case, this is not an issue with this plugin, and will occur regardless.
